jwt:
  token-exp-time: 432_000_000 # 5 days
  secret: 'ksfhlksjlkesjl;jksl;kfldskdl;ksfl;ks65456s465f4ds68f4dsf46ds4f5snkldj+dlksfnklslsjdkfljsdkkl;8798456dtycghcn,jhfhgcghxfgzdgzfcnbnmvnbvhncgh,cgxsdbjskabjksdbjb9890762176'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/blogger_db?useSSL=false
    username: blogger
    password: blogger
  jpa:
    show-sql: true

  flyway:
    locations: "classpath:db/migration/{vendor}"

