spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/blogger_db?useSSL=false
    username: blogger
    password: blogger
  jpa:
    show-sql: true
